name: Build pve-kernel (docker)

on:
  workflow_dispatch:
    #inputs:
    #  debug_enabled:
    #    type: boolean
    #    description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
    #    required: false
    #    default: false

env:
  REPO_URL: git://git.proxmox.com/git/pve-kernel.git
  REPO_BRANCH: pve-kernel-5.15
  UPLOAD_BIN_DIR: true

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    name: Build pve kernel
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker build
        uses: ./
        id: docker_build
        with:
          branch: ${REPO_BRANCH}

      - name: Print version string
        run: |
          echo "PVE kernel version: ${{ steps.docker_build.outputs.version }}"

      - name: Upload kernel directory
        uses: actions/upload-artifact@master
        if: steps.docker-build.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
        with:
          name: ${{ format('{0}-brunokc', steps.docker-build.outputs.version) }}
          path: pve-kernel/release
